<?php

use Codefy\Framework\Proxy\Codefy;

use function Codefy\Framework\Helpers\site_url;

?>
<!DOCTYPE html>
<html lang="<?=Codefy::$PHP->configContainer->string('app.language');?>">
<head>
    <base href="<?=site_url()?>">
    <meta charset="<?=Codefy::$PHP->configContainer->string('app.charset');?>">
    <link rel="stylesheet" type="text/css" href="<?=$this->url('assets/css/error.css');?>"/>
    <title>Error 404</title>
</head>
<body>
<div class="error-middle">
    <h1>Error 404 - Not Found</h1>
</div>
</body>
</html>
